version: '3.8'

services:
  pawcial-frontend:
    image: 192.168.0.79:5050/mustafaguven/pawcial-frontend:latest
    container_name: pawcial-frontend
    environment:
      # Nginx varsayılan olarak 80 portunda çalışır
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    ports:
      - "3000:80"  # Host:Container
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3
    networks:
      - pawcial-network

networks:
  pawcial-network:
    driver: bridge 

